from django.contrib.auth import get_user_model
from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(User)
admin.site.register(cat_especialidades)
admin.site.register(cat_escuelas)
admin.site.register(cat_genero)
admin.site.register(cat_parentesco)
admin.site.register(cat_medicamentos)
admin.site.register(cat_grupos_terapeuticos )
admin.site.register(cat_operaciones)
admin.site.register(cat_analisis)
admin.site.register(cat_enfermedades)
admin.site.register(cat_capitulos_enfermedades)
admin.site.register(cat_hospitalizaciones)
admin.site.register(cat_matetrial_curacion)
admin.site.register(cat_servicios)
admin.site.register(cat_ets )
admin.site.register(medical_staff)
admin.site.register(patients)
admin.site.register(alergies)
admin.site.register(operations)
admin.site.register(analysis)
admin.site.register(antecedentes_medicos)
admin.site.register(antecedentes_ginecologicos)
admin.site.register(indicadores_pre)
admin.site.register(consulta)
admin.site.register(receta)
admin.site.register(hospitalizacion)
admin.site.register(seguimiento )
admin.site.register(nota_medica)
admin.site.register(alta_hospitalizacion)
admin.site.register(solicitud_laboratorio )
admin.site.register(resultados_laboratorio )
admin.site.register(solicitud_especialista )
admin.site.register(solicitud_estudios )
admin.site.register(resultados_estudios )
admin.site.register(solicitud_operacion )
admin.site.register(material_operacion)
admin.site.register(personal_operacion)
admin.site.register(material_areas )
admin.site.register(atencion_enfermeria)
admin.site.register(material_usado_enfermeria)
admin.site.register(pedir_material)
admin.site.register(farmacia)
admin.site.register(surtir_recetas)
admin.site.register(cita_paciente )
admin.site.register(cita_turno )
admin.site.register(mensajero)
