# Generated by Django 4.0.6 on 2022-08-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alta_hospitalizacion',
            name='motivo_alta',
            field=models.CharField(choices=[('Alta prematura', 'Alta prematura'), ('Alta médica por mejoría', 'Alta médica por mejoría'), ('Alta médica definitiva', 'Alta médica definitiva'), ('Alta por traslado', 'Alta por traslado'), ('Alta médica transitoria', 'Alta médica transitoria'), ('Alta médica voluntaria', 'Alta médica voluntaria'), ('Alta por abandono del tratamiento', 'Alta por abandono del tratamiento'), ('Alta forzosa', 'Alta forzosa'), ('Alta por defunción o fallecimiento', 'Alta por defunción o fallecimiento'), ('Alta por fuga', 'Alta por fuga'), ('Alta médica deportiva', 'Alta médica deportiva')], default='', max_length=100, verbose_name='Motivo de Alta'),
        ),
    ]
