# Generated by Django 4.0.6 on 2022-09-15 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0002_alta_hospitalizacion_motivo_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_paciente',
            name='id_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doctor/Especialista'),
        ),
    ]
