# Generated by Django 4.0.6 on 2022-09-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0003_alter_cita_paciente_id_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_paciente',
            name='id_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitapp.cita_turno', verbose_name='Hora de la Cita'),
        ),
    ]
