# Generated by Django 4.0.6 on 2022-09-16 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0004_alter_cita_paciente_id_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_paciente',
            name='id_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_Cita', to=settings.AUTH_USER_MODEL, verbose_name='Doctor/Especialista'),
        ),
        migrations.AlterField(
            model_name='cita_paciente',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente_Cita', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
        ),
    ]
