# Generated by Django 4.0.6 on 2022-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0005_alter_cita_paciente_id_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentes_ginecologicos',
            name='ets',
        ),
        migrations.AddField(
            model_name='antecedentes_ginecologicos',
            name='ets',
            field=models.ManyToManyField(to='hospitapp.cat_ets'),
        ),
    ]
