# Generated by Django 4.0.6 on 2022-09-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0006_remove_antecedentes_ginecologicos_ets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='user',
            field=models.IntegerField(verbose_name='Usuario'),
        ),
    ]
