# Generated by Django 4.0.6 on 2022-09-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0007_alter_antecedentes_ginecologicos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='FUM',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ultima Mestruacion'),
        ),
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='fua',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ultimo Aborto'),
        ),
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='fuc',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ultima Cesarea'),
        ),
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='fup',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ultimo Parto'),
        ),
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='fupapa',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ultimo Papanicolau'),
        ),
    ]
