# Generated by Django 4.0.6 on 2022-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0008_alter_antecedentes_ginecologicos_fum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='edad_menopausia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad que tuvo la menopausia'),
        ),
    ]
