# Generated by Django 4.0.6 on 2022-09-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0009_alter_antecedentes_ginecologicos_edad_menopausia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='problemas_sexo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Problemas Sexuales'),
        ),
    ]
