# Generated by Django 4.0.6 on 2022-09-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0010_alter_antecedentes_ginecologicos_problemas_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_staff',
            name='user',
            field=models.IntegerField(verbose_name='id de Usuario'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='user',
            field=models.IntegerField(verbose_name='id de Usuario'),
        ),
    ]
