# Generated by Django 4.0.6 on 2022-09-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0012_alter_alergies_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='user',
            field=models.IntegerField(verbose_name='id de Usuario'),
        ),
        migrations.CreateModel(
            name='operations_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='id de Usuario')),
                ('medico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitapp.medical_staff')),
                ('operacion_recibida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitapp.cat_operaciones', verbose_name='operacion recibida')),
            ],
            options={
                'verbose_name': 'Antecedente de Operaciones del Paciente',
                'verbose_name_plural': 'Antecedentes de Operaciones de los Pacientes',
            },
        ),
    ]
