# Generated by Django 4.0.6 on 2022-09-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0013_alter_operations_user_operations_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations_history',
            name='medico_responsable',
        ),
    ]
