# Generated by Django 4.0.6 on 2022-09-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0014_remove_operations_history_medico_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadores_pre',
            name='paciente',
            field=models.IntegerField(verbose_name='Paciente'),
        ),
    ]
