# Generated by Django 4.0.6 on 2022-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0015_alter_indicadores_pre_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='id_paciente',
            field=models.IntegerField(verbose_name='Paciente'),
        ),
    ]
