# Generated by Django 4.0.6 on 2022-10-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitapp', '0016_alter_consulta_id_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alta_hospitalizacion',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='FUM',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha de Ultima Mestruacion'),
        ),
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='fua',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha de Ultimo Aborto'),
        ),
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='fuc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha de Ultima Cesárea'),
        ),
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='fup',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha de Ultimo Parto'),
        ),
        migrations.AlterField(
            model_name='antecedentes_ginecologicos',
            name='fupapa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha de Ultimo Papanicolau'),
        ),
        migrations.AlterField(
            model_name='atencion_enfermeria',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cita_paciente',
            name='fecha_cita',
            field=models.CharField(max_length=10, verbose_name='Fecha de la cita'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='Fecha_caducidad',
            field=models.CharField(max_length=10, verbose_name='Fecha de caducidad'),
        ),
        migrations.AlterField(
            model_name='hospitalizacion',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='indicadores_pre',
            name='Fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='medical_staff',
            name='fecha_nac',
            field=models.CharField(max_length=10, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='mensajero',
            name='enviado',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='nota_medica',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='fecha_nac',
            field=models.CharField(max_length=10, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='resultados_estudios',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='resultados_laboratorio',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitud_especialista',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitud_estudios',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitud_laboratorio',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitud_operacion',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitud_operacion',
            name='fecha_programada',
            field=models.CharField(max_length=10, verbose_name='Fecha Programada'),
        ),
        migrations.AlterField(
            model_name='surtir_recetas',
            name='fecha_surtido',
            field=models.CharField(max_length=10, verbose_name='Fecha'),
        ),
    ]
