INSERT INTO "hospitapp_cat_servicios" ( "servicio") 
VALUES 
("Central de Equipos y Esterilización"),
("Estomatología"),
("Ginecología y obstetricia"),
("Médicas y quirúrgicas"),
("Quirúrgicas"),
("Medicina preventiva"),
("Planificación familiar"),
("Planificación familiar y ginecología"),
("Anestesiología y Neurología"),
("Anestesiología"),
("Biología de la reproducción y Ginecología"),
("Cardiología intervencionista"),
("Cardiología, de uso general"),
("Cardiología, de uso general. Cardiología intervencionista"),
("Cardiología, de uso general y cardiología intervencionista. Radiodiagnóstico"),
("Cardiología para diagnóstico"),
("Cirugía cardiotorácica y cardiovascular"),
("Cirugía cardiotorácica"),
("Cirugía cardiovascular"),
("Cardiología médica y quirúrgica"),
("Cirugía torácica y cardiovascular"),
("Cirugía general"),
("Cirugía general y Médicas y quirúrgicas"),
("Cirugía maxilofacial"),
("Cirugía maxilofacial y estomatología"),
("Cirugía reconstructiva"),
("Fisiología pulmonar y Médicas y quirúrgicas"),
("Fisiología pulmonar"),
("Ginecología"),
("Médicas"),
("Médicas y quirúrgicas neonatología"),
("Médicas y quirúrgicas e Inhaloterapia"),
("Médicas y quirúrgicas y Cirugía vascular"),
("Médicas y Quirúrgicas y Urología"),
("Nefrología o Cirugía General"),
("Nefrología, Pediatría o Cirugía General"),
("Nefrología o Urología"),
("Unidad de trasplantes"),
("Neurocirugía"),
("Neurocirugía, Neuroradiología y Terapia Neuroendovascular"),
("Oftalmología"),
("Otorrinolaringología"),
("Quirúrgicas."),
("Quirúrgicas y otorrinolaringología"),
("Quirúrgicas y Cirugía vascular"),
("Radiodiagnóstico"),
("Radiodiagnóstico o imagenología"),
("Radiodiagnóstico y Fisiología Pulmonar"),
("Radiodiagnóstico o Imagenología o Nefrología Pediátrica"),
("Radiodiagnóstico o Imagenología y Cardiología Intervencionista"),
("Traumatología y ortopedia"),
("Urología"),
("Materiales de uso diverso");