INSERT INTO "hospitapp_cat_grupos_terapeuticos" ( "nombre_grupo") 
VALUES 
("Dermatología"),
("Hematología"),
("Enfermedades Infecciosas y Parasitarias"),
("Analgesia"),
("Gineco-obstetricia"),
("Nutriología"),
("Oncología"),
("Neurología"),
("Cardiología"),
("Soluciones electrolíticas y substitutos del plasma"),
("Reumatología y Traumatología"),
("Psiquiatría"),
("Gastroenterología"),
("Neumología"),
("Enfermedades Infecciosas y Parasitarias"),
("Endocrinología y Metabolismo"),
("Anestesia"),
("Dermatología"),
("Intoxicaciones"),
("Nefrología y Urología"),
("Oftalmología"),
("Enfermedades inmunoalérgicas"),
("Soluciones electrolíticas y substitutos del plasma"),
("Reumatología y Traumatología"),
("Planificación Familiar"),
("Otorrinolaringología"),
("Nefrología y Urología"),
("Vacunas, Toxoides, Inmunoglobulinas, Antitoxinas.");