INSERT INTO "hospitapp_cat_ets" ( "Nombre") 
VALUES
("Sífilis."),
("Herpes genital."),
("Clamidia."),
("Virus del papiloma humano (VPH)."),
("Virus de inmunodeficiencia humana (VIH)."),
("Gonorrea."),
("Chancro."),
("Hepatitis A y B."),
("Tricomoniasis."),
("Condiloma acuminado."),
("Vaginosis bacteriana."),
("Molusco contagioso."),
("Candidiasis."),
("Pediculosis del pubis."),
("Granuloma inguinal."),
("Linfogranuloma venéreo."),
("Cervicitis mucopurulenta."),
("Enfermedad inflamatoria pélvica."),
("Uretritis gonocócica, no-gonocócica y persistente."),
("Mucocervicitis purulenta."),
("Enterocolitis."),
("Giardiasis.");